-- Your SQL goes here
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE account (
  id UUID PRIMARY KEY, 
  subscribed_at TIMESTAMP NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(25) NOT NULL,
  status BOOLEAN NOT NULL DEFAULT FALSE,
  auth_token UUID NOT NULL UNIQUE
)
